version: "3"

services:
  gradle:
    build:
      context: ../
      dockerfile: cd/dockerfiles/gradle-dockerfile
    image: gradlew

  unit:
    image: gradlew
    command: clean build
    volumes:
      - ..:/app/

  app:
    build:
      context: ../
      dockerfile: cd/dockerfiles/app-dockerfile
    image: app:1.0
    ports:
      - 8080:8080
